---
# list of applications to install
general:
  local_home: "{{ lookup('env','HOME') }}"

# homebrew applications
applications:
  - git
  - tree
  - httpie
  - curl
  - wget
  - vim

# homebrew cask applications
cask_applications:
  - google-chrome
  - slack
  - iterm2
  - caffeine
  - spotify
  - dashlane
  - pycharm-ce
  - teamviewer
  - sublime-text
  - microsoft-remote-desktop-beta

